const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
async function main() {
    const lotM = 'MARACUYA-260410-1623';
    const lotS = 'SANDIA-260408-1410';

    // Restore batch status
    await prisma.productionBatch.update({ where: { batchNumber: lotM }, data: { status: 'STAGE_1_BASE' } });
    await prisma.productionBatch.update({ where: { batchNumber: lotS }, data: { status: 'STAGE_1_BASE' } });

    // Restore note statuses. I don't remember exactly which ones were PENDING, so I'll just set the later ones to PENDING
    // For MARACUYA:
    const notesM = await prisma.assemblyNote.findMany({ where: { productionBatchId: (await prisma.productionBatch.findUnique({where:{batchNumber: lotM}})).id } });
    for (const n of notesM) {
        if (n.stageOrder >= 5) {
            await prisma.assemblyNote.update({ where: { id: n.id }, data: { status: 'PENDING' } });
        }
    }

    // For SANDIA: 
    // Stage 6 and 7 were actually COMPLETED by the operator. Stage 8 was EXECUTING. Stage 9 was PENDING.
    const notesS = await prisma.assemblyNote.findMany({ where: { productionBatchId: (await prisma.productionBatch.findUnique({where:{batchNumber: lotS}})).id } });
    for (const n of notesS) {
        if (n.stageOrder === 8) {
            await prisma.assemblyNote.update({ where: { id: n.id }, data: { status: 'EXECUTING' } });
        } else if (n.stageOrder === 9) {
            await prisma.assemblyNote.update({ where: { id: n.id }, data: { status: 'PENDING' } });
        }
    }

    // Revert FinishedLotStock so it's not duplicated
    const m360 = await prisma.product.findFirst({ where: { name: 'SIROPE GENIALITY SABOR A MARACUYA X 360 ML' } });
    const m1000 = await prisma.product.findFirst({ where: { name: 'SIROPE GENIALITY SABOR A MARACUYA X 1000 ML' } });
    const s360 = await prisma.product.findFirst({ where: { name: 'SIROPE GENIALITY SABOR A SANDIA X 360 ML' } });
    const s1000 = await prisma.product.findFirst({ where: { name: 'SIROPE GENIALITY SABOR A SANDIA X 1000 ML' } });

    // Delete what we created in FinishedLotStock for Maracuya
    await prisma.finishedLotStock.deleteMany({
        where: { lotNumber: lotM }
    });
    // For Sandia, maybe we delete what we forced?
    // Wait, the operator had already finished 1000ML for Sandia. That means stock was legitimately generated by the back-end when they completed Ensamble!
    // But since I forced a new one or upserted it, maybe I shouldn't delete Sandia's. Let's just delete the ones that I know weren't finished (Maracuya 360, 1000, and Sandia 360).
    await prisma.finishedLotStock.deleteMany({
        where: { productId: m360.id, lotNumber: lotM }
    });
    await prisma.finishedLotStock.deleteMany({
        where: { productId: m1000.id, lotNumber: lotM }
    });
    await prisma.finishedLotStock.deleteMany({
        where: { productId: s360.id, lotNumber: lotS }
    });
    console.log("Restored batches back to panel.");
}
main().catch(console.error).finally(() => prisma.$disconnect());
