const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

exports.getBatchMonitorData = async (req, res) => {
    try {
        const { limit = 20, status } = req.query;
        // Limit query to recent Geniality batches (Only master Siropes - 1402)
        // Master batches often use `outputTargets` instead of direct `productId`
        const where = {
            OR: [
                { product: { accountGroup: 1402 } },
                { outputTargets: { some: { product: { accountGroup: 1402 } } } }
            ]
        };

        if (status) where.status = status;

        const batches = await prisma.productionBatch.findMany({
            where,
            orderBy: { createdAt: 'desc' },
            take: Number(limit),
            include: {
                product: true,
                assemblyNotes: {
                    include: {
                        processType: true,
                        completedBy: { select: { name: true } },
                        items: {
                            include: { component: { select: { name: true, sku: true, unit: true } } }
                        },
                        rpaExecutions: {
                            orderBy: { startedAt: 'desc' },
                            take: 1
                        }
                    },
                    orderBy: { stageOrder: 'asc' }
                },
                finishedLotStocks: {
                    include: { product: { select: { name: true, sku: true } } }
                }
            }
        });

        // Resolve MaterialLots mapping:
        // Because intermediate MaterialLots generated by Geniality have lotNumber == batch.batchNumber
        const batchNumbers = batches.map(b => b.batchNumber).filter(Boolean);
        const materialLots = await prisma.materialLot.findMany({
            where: { lotNumber: { in: batchNumbers } },
            include: { product: { select: { name: true, accountGroup: true } } }
        });

        const formatted = batches.map(batch => {
            const batchNotes = batch.assemblyNotes || [];
            
            // Map bases (G_ENSAMBLE or PESAJE related to base)
            const baseNotes = batchNotes.filter(n => 
                n.stageName?.toLowerCase().includes('base') || 
                n.product?.name?.toLowerCase().includes('base') ||
                n.targetQuantity > 100 // usually bases are massive
            ); // Since stage mapping can be loose, let's group by typical names
            
            // Wait, standardizing the stage is safer:
            const pesajeNota = batchNotes.find(n => n.processType?.code === 'PESAJE' || n.processType?.code === 'G_PESAJE');
            const ensambleBase = batchNotes.find(n => n.processType?.code === 'G_ENSAMBLE' && !n.stageName?.toLowerCase().includes('saborz'));
            const saborizacion = batchNotes.find(n => n.processType?.code === 'G_ENSAMBLE' && n.stageName?.toLowerCase().includes('saborz'));
            // Actually, Saborización is often a PESAJE step.
            const sabs = batchNotes.filter(n => n.stageName?.toLowerCase().includes('sabor') || n.processType?.code === 'SABORIZACION');

            const empaqueNotes = batchNotes.filter(n => n.processType?.code === 'G_EMPAQUE' || n.processType?.code === 'EMPAQUE');

            // Find matching material lots for this batch's bases
            const batchMatLots = materialLots.filter(ml => ml.lotNumber === batch.batchNumber);

            return {
                id: batch.id,
                batchNumber: batch.batchNumber,
                product: batch.product?.name || 'Geniality Product',
                status: batch.status,
                createdAt: batch.createdAt,
                base: {
                    pesaje: pesajeNota,
                    ensamble: ensambleBase,
                    materialLots: batchMatLots
                },
                saborizacion: sabs,
                empaque: {
                    notes: empaqueNotes,
                    finishedStocks: batch.finishedLotStocks
                },
                allNotes: batchNotes // for full drill-down
            };
        });

        res.json({ ok: true, batches: formatted });
    } catch (e) {
        console.error('[genialityMonitorController]', e);
        res.status(500).json({ error: e.message });
    }
};
